# Generated by Django 4.1.1 on 2022-10-03 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/products/')),
                ('material', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512)),
                ('blankPriceRows', models.CharField(max_length=512)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'xs'), ('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('2XL', '2xl'), ('3XL', '3xl'), ('4XL', '4xl')], max_length=8)),
                ('description', models.CharField(max_length=32, null=True)),
                ('value', models.CharField(max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='PrintArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('front', 'front'), ('back', 'back'), ('left', 'left'), ('right', 'right')], max_length=8)),
                ('xPos', models.IntegerField()),
                ('yPos', models.IntegerField()),
                ('xSize', models.IntegerField()),
                ('ySize', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('front', 'front'), ('back', 'back'), ('left', 'left'), ('right', 'right')], max_length=8)),
                ('type', models.CharField(choices=[('image', 'image'), ('text', 'text')], max_length=8)),
                ('xPos', models.IntegerField()),
                ('yPos', models.IntegerField()),
                ('aspectRatio', models.FloatField()),
                ('size', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('rotation', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/layers/')),
                ('textContent', models.CharField(max_length=64, null=True)),
                ('textSize', models.IntegerField(null=True)),
                ('translateX', models.IntegerField(null=True)),
                ('translateY', models.IntegerField(null=True)),
                ('textColor', models.CharField(max_length=16, null=True)),
                ('textBoxX', models.IntegerField(null=True)),
                ('textBoxY', models.IntegerField(null=True)),
                ('textBoxW', models.IntegerField(null=True)),
                ('textBoxH', models.IntegerField(null=True)),
                ('textBoxAdvance', models.IntegerField(null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.design')),
                ('font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.font')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('minQty', models.IntegerField()),
                ('maxQty', models.IntegerField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('gray', 'gray'), ('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
