# Generated by Django 4.1.1 on 2022-10-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='blankPriceRows',
        ),
    ]
