# Generated by Django 4.1.1 on 2022-10-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_blankpricerows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='description',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('front', 'front'), ('back', 'back'), ('left', 'left'), ('right', 'right')], max_length=8)),
                ('image', models.ImageField(upload_to='images/products/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
