# Generated by Django 4.1.1 on 2022-10-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productimage_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='maxQty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
