# Generated by Django 4.1.1 on 2022-10-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_color_product_alter_discount_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='shop.design'),
        ),
    ]
