# Generated by Django 4.1.1 on 2022-10-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_layer_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='zIndex',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
