# Generated by Django 4.1.1 on 2022-10-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='design',
            field=models.ForeignKey(default=43, on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='shop.design'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preview',
            name='side',
            field=models.CharField(choices=[('front', 'front'), ('back', 'back'), ('left', 'left'), ('right', 'right')], default=1, max_length=8),
            preserve_default=False,
        ),
    ]
