# Generated by Django 4.1.1 on 2022-10-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_design_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveryStatus',
        ),
    ]
