# Generated by Django 4.1.1 on 2022-10-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_order_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
