# Generated by Django 4.1.1 on 2022-10-22 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('line1', models.CharField(max_length=128)),
                ('line2', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='deliveryAddress',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.shippingdetails'),
        ),
    ]
