# Generated by Django 4.1.1 on 2022-10-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_designmockups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignMockups',
            new_name='DesignMockup',
        ),
    ]
