# Generated by Django 4.1.1 on 2022-10-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rename_designmockups_designmockup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designmockup',
            name='image',
            field=models.ImageField(null=True, upload_to='images/mockups/'),
        ),
    ]
