# Generated by Django 4.1.1 on 2022-10-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_font_language_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='image',
            field=models.FileField(null=True, upload_to='images/layers/'),
        ),
    ]
