# Generated by Django 4.1.1 on 2022-12-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_layer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(default='price_1LvIkfK3DYcQUrRXNoMcP7c9', max_length=64),
            preserve_default=False,
        ),
    ]
