# Generated by Django 4.1.1 on 2022-12-06 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stripe_id',
            new_name='stripe_price_id',
        ),
    ]
