# Generated by Django 4.1.1 on 2022-12-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_stripe_id_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(default='prod_MebyqVT2sUkIre', max_length=64),
            preserve_default=False,
        ),
    ]
